### PR TITLE
distros: opensuse/leap: add Dockerfile

### PR DESCRIPTION
**Pull request by jenting**
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for your contribution.

Before to merge it, I am not too familiar with Suse release cycles, but looking around I see version 15 is like LTS, if that is the case I would avoid to have minor releases like 15.x since this is mostly for packaging. 

comments ?

**Comment by jenting** [comment]
> thanks for your contribution.
> 
> Before to merge it, I am not too familiar with Suse release cycles, but looking around I see version 15 is like LTS, if that is the case I would avoid to have minor releases like 15.x since this is mostly for packaging.
> 
> comments ?

No problem for me. I will remove 15.1.

**Comment by edsiper** [comment]
just let's call it suse/15

**Comment by jenting** [comment]
> just let's call it suse/15

Change to opensuse/leap, okay?

**Comment by edsiper** [comment]
thanks!

**Pull request merged**
